# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-trace-python Documentation for the list of available functions.

import os
import sys

sys.path.append(os.environ['PERF_EXEC_PATH'] + \
        '/scripts/python/Perf-Trace-Util/lib/Perf/Trace')

from perf_trace_context import *
from Core import *


def trace_begin():
    pass
#print "in trace_begin"

def trace_end():
    pass
#print "in trace_end"

def trace_unhandled(event_name, context, event_fields_dict):
    print ' '.join(['%s=%s'%(k,str(v))for k,v in sorted(event_fields_dict.items())])

def print_header(event_name, cpu, secs, nsecs, pid, comm):
    print "%-20s %5u %05u.%09u %8u %-20s " % \
            (event_name, cpu, secs, nsecs, pid, comm),

def process_event(param_dict):
    sample = param_dict['sample']
    try:
        print "%s;%d;%ld;%d;%s;%s;%s" % \
              (param_dict['comm'],
              sample['pid'],
              sample['time'],
              sample['period'],
              param_dict['ev_name'],
              param_dict['dso'],
              param_dict['symbol']
              )
    except:
        pass

# 'symbol': 'writeBinTracks', 'sample': {'ip': 4225457L, 'pid': 194823, 'period':
#     2772556L, 'time': 3356447618636342L, 'tid': 194823, 'cpu': 4294967295},
# 'dso': '/data/oawile/cl_forward/bin/x86_64/Release/clpixel', 'comm': 'clpixel',
# 'ev_name': 'cycles', 'raw_buf': '', 'callchain': []}
